Adding examples for local-retail with version 1.x
beckn/local-retail pull request #4
Opened 2023-12-05 09:48 UTC by rajaneeshk90

2023-12-19 15:45 UTC, emmayank requested changes
Hi @rajaneeshk90 ,

I have completed the review of your pull request and overall, it looks good and ready for merging into the `draft`. I found a few minor issues that require attention. Please address these issues and update the pull request accordingly.

Thank you for your efforts, and I appreciate your prompt attention to these matters.

Best regards,
@emmayank

2023-12-19 15:45 UTC, emmayank commented on docs/3_Scope.md
> +## Use Cases In Scope
Mention In Scope Items as : 

1. Buying & Seller of Grocery
2. Buying & Seller of Electronic Items
3. uying & Seller of F&B

2023-12-19 15:45 UTC, emmayank commented on docs/3_Scope.md
> +## Use Cases Out of Scope
Mention Out of Scope as : 
1. Repair of Item
2. Buying & Selling at Bulk
3. Buying & Selling of any Financial service

2023-12-19 15:45 UTC, emmayank commented on docs/README.md
> +    - [Courses](./implementation-guide/1_local-retail.md)
Instead of [course], mention local-retail and use correct hyperlink

2023-12-19 15:45 UTC, emmayank commented on docs/implementation-guide/1_local-retail.md
> +- REQUIRED. Any retail service provider-related information like name, logo, short description must be mapped to the `Provider.descriptor` schema
Any retail `service` provider-related, // remove service word

2023-12-19 15:45 UTC, emmayank commented on docs/implementation-guide/1_local-retail.md
> +## 1.2 Application for local-retail
Initiating Purchase for Local-retail

2023-12-19 15:45 UTC, emmayank commented on docs/implementation-guide/1_local-retail.md
> +#### 1.2.1.1 Selecting a retail service from the catalog
retail ~service~ product

2023-12-19 15:45 UTC, emmayank commented on docs/implementation-guide/1_local-retail.md
> +#### 1.2.1.2 Initializing a retail service
Initializing a retail ~service~ order

2023-12-19 15:45 UTC, emmayank commented on docs/implementation-guide/1_local-retail.md
> +#### 1.2.1.3 Confirming the retail service
onfirming the retail ~service~ order

2023-12-19 15:45 UTC, emmayank commented on docs/implementation-guide/1_local-retail.md
> +#### 1.2.1.1 Selecting a retail service from the catalog
#### 1.2.1.1 Selecting a retail ~service~ item from the catalog

2023-12-19 15:45 UTC, emmayank commented on docs/implementation-guide/1_local-retail.md
> +#### 1.2.2.2  Initializing a retail service
#### 1.2.2.2  Initializing a retail order ~service~

2023-12-19 15:45 UTC, emmayank commented on docs/implementation-guide/1_local-retail.md
> +#### 1.2.2.3 Confirming the retail service
#### 1.2.2.3 Confirming the retail ~service~ order

2023-12-19 15:45 UTC, emmayank commented on docs/implementation-guide/1_local-retail.md
> +## 1.3 Fulfillment of retail Services
## 1.3 Fulfillment of retail ~Services~ Order

2023-12-19 15:45 UTC, emmayank commented on docs/implementation-guide/1_local-retail.md
> +#### 1.3.1.2 Updating a retail service
Updating a retail ~service~ order

2023-12-19 15:45 UTC, emmayank commented on docs/implementation-guide/1_local-retail.md
> +#### 1.3.1.3 Cancelling a retail service
Cancelling a retail ~service~ order

2023-12-19 15:45 UTC, emmayank commented on docs/implementation-guide/1_local-retail.md
> +#### 1.3.2.2 Updating a retail services
Updating a retail ~services~ order

2023-12-19 15:45 UTC, emmayank commented on docs/implementation-guide/1_local-retail.md
> +#### 1.3.2.3 Cancelling a retail services
Cancelling a retail ~services~ order

2023-12-19 15:45 UTC, emmayank commented on docs/implementation-guide/1_local-retail.md
> +## 1.4 Post-fulfillment of retail Services
Post-fulfillment of retail ~Services~ Order

2023-12-21 10:24 UTC, rajaneeshk90 commented
HI @emmayank 

Thanks for your effort in reviewing this PR. 
I have gone through and have made the suggested changes. Please have a look.

Thanks,
Rajaneesh

2023-12-21 12:02 UTC, merged